### ISSUE TITLE
Cannot read property 'US' of undefined - the window.paypal.config.locales variable is not defined

### ISSUE THREAD

**Issue by xdejonghe-viseo** [paypal/paypal-checkout-components#1114]
### Description

It seems that the global variable **window.paypal.config.locales** does not longer exist in global scope but the file https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js?build=x continue to use it and that generates an error.

This error rises since version **4.0.269**.

**Error**

{err: "TypeError: Cannot read property 'US' of undefined↵…D&uid=cb3b712850&version=min&xcomponent=1:1212:32", timestamp: 1558505735639, windowID: "c98824c62e", pageID: "9ec51122e6", prev_corr_ids: "", …}
country: "US"
env: "sandbox"
err: "TypeError: Cannot read property 'US' of undefined↵    at https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js?build=x:4025:54↵    at Function.e.try (https://www.paypalobjects.com/api/checkout.min.js:1:19395)↵    at exports.determineLocale (https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js?build=x:4021:45)↵    at setupButton (https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js?build=x:3777:41)↵    at https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js?build=x:3611:24↵    at Function.e.try (https://www.paypalobjects.com/api/checkout.min.js:1:19395)↵    at exports.setup (https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js?build=x:3610:45)↵    at https://www.sandbox.paypal.com/webapps/hermes/button?env=sandbox&commit=true&style.color=silver&style.shape=rect&style.label=pay&style.size=medium&style.tagline=false&domain=XXXXXXXXXX.com&sessionID=XXXXXXXXXX&buttonSessionID=XXXXXXXXXX&funding.disallowed=venmo&funding.remembered=paypal&locale.x=en_US&logLevel=warn&sdkMeta=eyJ1cmwiOiJodHRwczovL3d3dy5wYXlwYWxvYmplY3RzLmNvbS9hcGkvY2hlY2tvdXQubWluLmpzIn0%3D&uid=XXXXXX&version=min&xcomponent=1:1212:32"
host: "www.sandbox.paypal.com"
lang: "en"
pageID: "9ec51122e6"
path: "/webapps/hermes/button"
prev_corr_ids: ""
referer: "https://XXXXXXXXXX.com"
timestamp: 1558505735639
uid: "20a6643f1b_mdy6mdk6mja"
ver: "4.0.270"
windowID: "c98824c62e"
__proto__: Object

file : https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js?build=x
invalid code: 
`    "./public/js/button/locale.js": function(module, exports, __webpack_require__) {
        "use strict";
        exports.__esModule = !0;
        exports.determineLocale = function() {
            return window.paypal.Promise.try(function() {
                var userLocale = window.xprops.locale;
                if (userLocale) {
                    var _userLocale$split = userLocale.split("_"), lang = _userLocale$split[0], country = _userLocale$split[1];
                    if (!window.paypal.config.locales[country]) throw new Error("Invalid country: " + country + " for locale " + userLocale);
                    if (-1 === window.paypal.config.locales[country].indexOf(lang)) throw new Error("Invalid language: " + lang + " for locale " + userLocale);
                    return {
                        lang: lang,
                        country: country
                    };
                }
                return (0, _api.getLocale)();
            });
        };
        var _api = __webpack_require__("./public/js/button/api.js");
    },`

### Steps to reproduce

Load the file https://www.paypalobjects.com/api/checkout.js

### Affected browsers

- [x] Chrome
- [ ] Safari
- [x] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment]
Thanks for the report. Rolling out a fix.

**Comment by xdejonghe-viseo** [comment]
The issue is fixed, thank you for your speed

**Comment by AdamKochanski** [comment]
This issue still occur 

`logger.js:63 ppxo_xo_buttonjs_bootstrap_err 
{err: "TypeError: Cannot read property 'PL' of undefined↵…d=71a0f997d8&version=4.0.270&xcomponent=1:1209:32", timestamp: 1564060833281, windowID: "8bb2a5ad49", pageID: "d06be0bc09", prev_corr_ids: "", …}
country: "US"
env: "sandbox"
err: "TypeError: Cannot read property 'PL' of undefined↵    at https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js?build=x:4026:54↵    at Function.ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.4.0.270.js:875:33)↵    at exports.determineLocale (https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js?build=x:4022:45)↵    at setupButton (https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js?build=x:3778:41)↵    at https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js?build=x:3612:24↵    at Function.ZalgoPromise.try (https://www.paypalobjects.com/api/checkout.4.0.270.js:875:33)↵    at exports.setup (https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js?build=x:3611:45)↵    at https://www.sandbox.paypal.com/webapps/hermes/button?env=sandbox&commit=true&style.label=checkout&style.size=responsive&style.shape=rect&style.color=gold&domain=localhost%3A8082&sessionID=8d865572cc_mtm6mtg6mdq&buttonSessionID=c06680da21_mtm6mja6mza&funding.disallowed=venmo&locale.x=pl_PL&logLevel=warn&sdkMeta=eyJ1cmwiOiJodHRwczovL3d3dy5wYXlwYWxvYmplY3RzLmNvbS9hcGkvY2hlY2tvdXQuNC4wLjI3MC5qcyJ9&uid=71a0f997d8&version=4.0.270&xcomponent=1:1209:32"
host: "www.sandbox.paypal.com"
lang: "en"
pageID: "d06be0bc09"
path: "/webapps/hermes/button"
prev_corr_ids: ""
referer: "http://localhost:8082"
timestamp: 1564060833281
uid: "8d865572cc_mtm6mtg6mdq"
ver: "4.0.270"
windowID: "8bb2a5ad49"
__proto__: Object`
