### ISSUE TITLE
[Bug] React driver throws deprecation warning in StrictMode

### ISSUE THREAD

**Issue by dotku** [paypal/paypal-checkout-components#1448]
### 🐞 Describe the Bug

I use the code from here as a sample
https://github.com/paypal/paypal-checkout-components/blob/master/demo/react.htm

But I got the error report with content:

> findDOMNode is deprecated in StrictMode

![image](https://user-images.githubusercontent.com/1519232/95458348-e593ad80-0926-11eb-9b16-b2089747e9d1.png)

### 🤔 Expected Behavior
Should not have an error report

### 🌍 Environment

- Browser version: - Chrome
- OS version: - MackOS
- SDK version (`window.paypal.version`): -

**Comment by gregjopa** [comment]
Hi @dotku to get around this warning you can use useRef() instead of the zoid react driver.

Also, we just released a react library to simplify this style of integration: https://github.com/paypal/react-paypal-js.

**Comment by mayur-keswani** [comment]
The current version is still having this issue. Pls resolve this

**Comment by developithecus** [comment]
> Hi @dotku to get around this warning you can use useRef() instead of the zoid react driver.
> 
> Also, we just released a react library to simplify this style of integration: https://github.com/paypal/react-paypal-js.

I don't think this issue is worth closing, though. I found myself experiencing the same issue while using the `braintree-web :: paypalCheckout` API. I cannot however currently see a way to easily integrate `react-paypal-js` with `braintree-web` by doing this (since I don't directly use paypal client Ids in my app and neither am I happy with adding those as env vars).
